# Generated by Django 4.2.7 on 2023-11-29 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aziende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Budget Type',
                'verbose_name_plural': 'Budget Types',
            },
        ),
        migrations.CreateModel(
            name='TargetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('question_lia', models.TextField(blank=True, null=True, verbose_name='Question for LIA')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Title')),
                ('project_type', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='open', max_length=10, verbose_name='Project Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(limit_choices_to={'industry__id': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='supported_projects', to='aziende.company', verbose_name='Supporting Entity')),
                ('lead_partne', models.ManyToManyField(limit_choices_to={'industry__id': 2}, related_name='lead_projects', to='aziende.company', verbose_name='Lead Partner')),
                ('partner', models.ManyToManyField(limit_choices_to={'industry__id': 2}, related_name='partnered_projects', to='aziende.company', verbose_name='Partners')),
                ('supporters', models.ManyToManyField(limit_choices_to={'industry__id': 4}, related_name='supporting_projects', to='aziende.company', verbose_name='Supporters')),
                ('target', models.ManyToManyField(blank=True, to='lai_projects.targetproject', verbose_name='Project Targets')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Budget Title')),
                ('year', models.PositiveIntegerField(default=2023, verbose_name='Year')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_years', to='lai_projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Budget Year',
                'verbose_name_plural': 'Budget Years',
            },
        ),
        migrations.CreateModel(
            name='BudgetObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(verbose_name='Target Value')),
                ('control_date', models.DateField(verbose_name='Control Date')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='lai_projects.budget', verbose_name='Budget')),
            ],
            options={
                'verbose_name': 'Budget Objective',
                'verbose_name_plural': 'Budget Objectives',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='lai_projects.budgettype', verbose_name='Budget Type'),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='lai_projects.budgetyear', verbose_name='Budget Year'),
        ),
    ]
