# Generated by Django 4.2.7 on 2023-11-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company default', max_length=255, verbose_name='Company Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('macro_switch', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Specify whether the company is public or private.', max_length=10, verbose_name='Macro Switch')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Company Representative default', max_length=254, verbose_name='Full Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('civic_number', models.CharField(max_length=10, verbose_name='Civic Number')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='Newsletter Subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aziende.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'company representative',
                'verbose_name_plural': 'company representatives',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istat_code', models.CharField(max_length=10, verbose_name='ISTAT Code')),
                ('name_it', models.CharField(max_length=100, verbose_name='Name (IT)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('at_code', models.CharField(max_length=10, verbose_name='AT Code')),
                ('unsd_code', models.CharField(max_length=10, verbose_name='UNSD Code')),
                ('iso_alpha2_code', models.CharField(max_length=2, verbose_name='ISO Alpha-2 Code')),
                ('iso_alpha3_code', models.CharField(max_length=3, verbose_name='ISO Alpha-3 Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Type')),
                ('descrizione', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'File Type',
                'verbose_name_plural': 'File Types',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Industry Name')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100, verbose_name='Municipality')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('tax_code', models.CharField(max_length=11, verbose_name='Tax Code')),
                ('postal_code_from', models.CharField(max_length=5, verbose_name='Postal Code From')),
                ('postal_code_to', models.CharField(max_length=5, verbose_name='Postal Code To')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'municipality and province',
                'verbose_name_plural': 'municipalities and provinces',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Sector Name')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Date From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.companyrepresentative', verbose_name='Company Representative')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'role history',
                'verbose_name_plural': 'role histories',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifier')),
                ('is_legal', models.BooleanField(verbose_name='Is Legal')),
                ('is_operative', models.BooleanField(verbose_name='Is Operative')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('civic_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Civic Number')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='aziende.company', verbose_name='Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.country', verbose_name='Country')),
                ('municipality_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.municipalityprovince', verbose_name='Municipality Province')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
            },
        ),
        migrations.AddField(
            model_name='companyrepresentative',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='companyrepresentative',
            name='municipality_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.municipalityprovince', verbose_name='Municipality Province'),
        ),
        migrations.AddField(
            model_name='companyrepresentative',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aziende.role', verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company/', verbose_name='File')),
                ('descrizione', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='aziende.company', verbose_name='Company')),
                ('tipo_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_files', to='aziende.filetype', verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Company File',
                'verbose_name_plural': 'Company Files',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aziende.industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aziende.sector', verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('alert', models.BooleanField(default=False, verbose_name='Alert')),
                ('visible_to_all', models.BooleanField(default=False, verbose_name='Visible to All')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.activitytype', verbose_name='Activity Type')),
                ('activity_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Activity User')),
                ('company_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.companyrepresentative', verbose_name='Company Representative')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
