# Generated by Django 4.2.7 on 2023-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfile',
            name='file',
            field=models.FileField(upload_to='files_aziende/', verbose_name='File'),
        ),
    ]
