# Generated by Django 4.2.7 on 2023-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0002_alter_companyfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='office',
            name='phone',
        ),
        migrations.AddField(
            model_name='office',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
