# Generated by Django 4.2.7 on 2023-11-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0003_remove_office_mobile_remove_office_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='office',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
    ]
