# Generated by Django 4.2.7 on 2023-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0004_rename_phone_number_office_phone_office_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrepresentative',
            name='mobile',
        ),
        migrations.AddField(
            model_name='company',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
    ]
