# Generated by Django 4.2.7 on 2023-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0005_remove_companyrepresentative_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrepresentative',
            name='phone',
        ),
        migrations.AddField(
            model_name='companyrepresentative',
            name='phone_mobile',
            field=models.CharField(default='340123456789', max_length=20, verbose_name='phone_mobile'),
        ),
        migrations.AddField(
            model_name='companyrepresentative',
            name='phone_number',
            field=models.CharField(default='011123456789', max_length=20, verbose_name='phone_number'),
        ),
    ]
