# Generated by Django 4.2.7 on 2023-12-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0006_remove_companyrepresentative_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Number_employees',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Number of employees'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Attiva', 'Attiva'), ('Sospesa', 'Sospesa')], default='Attiva', help_text='Specify whether the company is Attiva or Sospesa.', max_length=10, verbose_name='Status'),
        ),
    ]
