# Generated by Django 4.2.7 on 2023-12-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0007_company_number_employees_company_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Number_employees',
            new_name='number_employees',
        ),
    ]
