# Generated by Django 4.2.7 on 2023-12-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aziende', '0008_rename_number_employees_company_number_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrepresentative',
            name='status',
            field=models.CharField(choices=[('Attiva', 'Attiva'), ('Sospesa', 'Sospesa')], default='Attiva', help_text='Specify whether the company is Attiva or Sospesa.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of employees'),
        ),
    ]
