# Generated by Django 4.2.7 on 2023-11-29 15:33

from django.db import migrations, models
import django.db.models.deletion
import job_candidates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0001_initial'),
        ('aziende', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('vacancy_start_date', models.DateField(verbose_name='Vacancy Start Date')),
                ('study_title', models.CharField(max_length=255, verbose_name='Study Title')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Birth Place')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('civic_number', models.CharField(max_length=10, verbose_name='Civic Number')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('whatsapp', models.BooleanField(verbose_name='WhatsApp')),
                ('facebook', models.CharField(max_length=255, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('tiktok', models.CharField(max_length=255, verbose_name='TikTok')),
                ('license', models.BooleanField(verbose_name="Driver's License")),
                ('car_owned', models.BooleanField(verbose_name='Car Owned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.country', verbose_name='Country')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.jobtype', verbose_name='Job Type')),
                ('municipality_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.municipalityprovince', verbose_name='Municipality Province')),
                ('protected_category', models.ManyToManyField(to='vacancies.protectedcategory', verbose_name='Protected Category')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Type')),
                ('descrizione', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Candidate File Type',
                'verbose_name_plural': 'Candidate File Types',
            },
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(verbose_name='Interview Date')),
                ('interviewer', models.CharField(max_length=255, verbose_name='Interviewer')),
                ('verbal_evaluation', models.TextField(verbose_name='Verbal Evaluation')),
                ('star_rating', models.IntegerField(verbose_name='Star Rating')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job_candidates.candidate', verbose_name='Candidate')),
                ('interview_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_candidates.interviewtype', verbose_name='Interview Type')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewCandidateVcancyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(verbose_name='Interview Date')),
                ('verbal_evaluation', models.TextField(verbose_name='Verbal Evaluation')),
                ('star_rating', models.IntegerField(verbose_name='Star Rating')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_candidate', to='job_candidates.candidate', verbose_name='Candidate')),
                ('interview_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_candidates.interviewtype', verbose_name='Interview Type')),
                ('vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews_vacanciy', to='vacancies.vacancy', verbose_name='Vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Candidate History',
                'verbose_name_plural': 'Vacancy Candidates History',
            },
        ),
        migrations.CreateModel(
            name='CandidatePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='candidate_pdfs/', validators=[job_candidates.models.validate_file_extension], verbose_name='PDF File')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_file', to='job_candidates.candidate', verbose_name='Candidate CV')),
            ],
            options={
                'verbose_name': 'Candidate Curriculum PDF',
                'verbose_name_plural': 'Candidate Curriculum PDFs',
            },
        ),
        migrations.CreateModel(
            name='CandidateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='candidate/files', verbose_name='File')),
                ('descrizione', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='job_candidates.candidate', verbose_name='Candidate Files')),
                ('tipo_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_files', to='job_candidates.candidatefiletype', verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Candidate Generic File',
                'verbose_name_plural': 'Candidate Generic Files',
            },
        ),
        migrations.CreateModel(
            name='CandidateCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_custom_field_values', to='job_candidates.candidate')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.customfield')),
            ],
        ),
    ]
