# Generated by Django 4.2.7 on 2023-11-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('date', 'Date'), ('string', 'String'), ('text', 'Text'), ('enum', 'Enum'), ('set', 'Set')], max_length=50, verbose_name='Field Type')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='Default Value')),
                ('question_lia', models.TextField(blank=True, null=True, verbose_name='Question for LIA')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisiti',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Gruppo Requisiti',
                'verbose_name_plural': 'Gruppi Requisiti',
            },
        ),
        migrations.CreateModel(
            name='VacancyCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.customfield')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyCustomFieldRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(verbose_name='Is Required')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.customfield')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_requirements', to='vacancies.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='utils.customfield')),
            ],
        ),
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='utils.customfieldgroup'),
        ),
    ]
